"""empty message

Revision ID: c1af25622276
Revises: None
Create Date: 2016-02-15 20:57:19.097003

"""

# revision identifiers, used by Alembic.
revision = 'c1af25622276'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nutrient_goals', sa.Column('show_on_graph', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nutrient_goals', 'show_on_graph')
    ### end Alembic commands ###
