"""empty message

Revision ID: f9cc8b7376f0
Revises: None
Create Date: 2016-02-15 20:22:00.325908

"""

# revision identifiers, used by Alembic.
revision = 'f9cc8b7376f0'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    ### end Alembic commands ###
